# Generated by Django 4.2.7 on 2023-11-30 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'мелкий пакет'), (1, 'посылка'), (3, 'посылка 1 Модельа'), (4, 'посылка международная'), (5, 'ценная посылка'), (6, 'экспресс-посылка')], default=1, verbose_name='тип посылки')),
                ('phone_number', models.CharField(max_length=50, verbose_name='телефон для извещения')),
                ('summary_price', models.IntegerField(default=0, verbose_name='сумма платежа')),
            ],
            options={
                'verbose_name': 'Посылка',
                'verbose_name_plural': 'Посылки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PostalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50, verbose_name='ФИО отправителя')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='ФИО получателя')),
                ('send_point', models.CharField(max_length=50, verbose_name='пункт отправки')),
                ('receive_point', models.CharField(max_length=50, verbose_name='пункт получения')),
                ('send_index', models.CharField(max_length=50, verbose_name='индекс места отправки')),
                ('receive_index', models.CharField(max_length=50, verbose_name='индекс места получения')),
            ],
            options={
                'verbose_name': 'Почтовое отправление',
                'verbose_name_plural': 'Почтовые отправления',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('postalitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.postalitem')),
                ('type', models.IntegerField(choices=[(0, 'письмо'), (1, 'заказное письмо'), (2, 'ценное письмо'), (3, 'экспресс-письмо')], default=0, verbose_name='тип письма')),
                ('weight', models.IntegerField(default=0, verbose_name='вес письма')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['-id'],
            },
            bases=('post.postalitem',),
        ),
    ]
