# Generated by Django 4.2.7 on 2023-11-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='id',
        ),
        migrations.AddField(
            model_name='parcel',
            name='postalitem_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.postalitem'),
            preserve_default=False,
        ),
    ]
